name: onnx
channels:
  - defaults
dependencies:
  - python==3.10.*
  - pip
  - pip:
    #- mpmath>=0.19
    #- pyreadline3
    #- humanfriendly>=9.1 
    - coloredlogs
    #- mpmath>=0.19 
    - sympy
    - numpy<1.24
    - flatbuffers
    - packaging 
    - protobuf<4
    - diffusers
    - transformers
    #- onnx
    - onnxruntime
    #- onnxruntime-directml
    - torch
    #- ftfy
    #- spacy
    - accelerate